apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .JobName }}-ingress"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /{{ .ModelId }}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: "{{ .JobName }}"
                port:
                  number: 80
