{{- if .AutoscalingEnabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .JobName }}-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .JobName }}-deployment"
  minReplicas: {{ .AutoscalingMin }}
  maxReplicas: {{ .AutoscalingMax }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
{{- end }}