apiVersion: v1
kind: PersistentVolume
metadata:
  name: { { .Values.persistence.pv.name } }
spec:
  capacity:
    storage: { { .Values.persistence.pv.storage } }
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: { { .Values.persistence.pv.path } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: { { .Values.persistence.pvc.name } }
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: { { .Values.persistence.pv.storage } }
  storageClassName: ""
  volumeName: { { .Values.persistence.pv.name } }
