apiVersion: v1
kind: Service
metadata:
  name: { { .Values.service.name } }
  labels:
    app: modelbazaar
spec:
  selector:
    app: modelbazaar
  ports:
    - name: http
      port: { { .Values.service.port } }
      targetPort: { { .Values.service.port } }
