{
 "title": "Clients",
 "tags": [
  "nomad",
  "nomad-clients"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(nomad_client_uptime, cluster)"
    }
   },
   { "name": "node_id", "label": "Node ID", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster,node_id) (nomad_client_host_cpu_total{cluster=\"$cluster\",node_id=\"$node_id\"}) / (sum by (cluster, node_id) (nomad_client_host_cpu_total{cluster=\"$cluster\",node_id=\"$node_id\"}) + sum by (cluster, node_id) (nomad_client_host_cpu_idle{cluster=\"$cluster\",node_id=\"$node_id\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Allocations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster, node_id) (nomad_client_allocated_cpu{cluster=\"$cluster\", node_id=\"$node_id\"}) / (sum by (cluster,node_id) (nomad_client_allocated_cpu{cluster=\"$cluster\", node_id=\"$node_id\"}) + sum by (cluster, node_id) (nomad_client_unallocated_cpu{cluster=\"$cluster\", node_id=\"$node_id\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster, node_id) (nomad_client_host_memory_used{cluster=\"$cluster\", node_id=\"$node_id\"}) / (sum by (cluster, node_id) (nomad_client_host_memory_total{cluster=\"$cluster\", node_id=\"$node_id\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster, node_id) (nomad_client_allocated_memory{cluster=\"$cluster\", node_id=\"$node_id\"}) / (sum by (cluster, node_id) (nomad_client_allocated_memory{cluster=\"$cluster\", node_id=\"$node_id\"}) + sum by (cluster, node_id) (nomad_client_unallocated_memory{cluster=\"$cluster\", node_id=\"$node_id\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilisation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster, node_id) (nomad_client_host_disk_used{cluster=\"$cluster\", node_id=\"$node_id\"}) / (sum by (cluster, node_id) (nomad_client_host_disk_size{cluster=\"$cluster\", node_id=\"$node_id\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "nomad_client_uptime{cluster=\"$cluster\"}",
     "legendFormat": "uptime"
    },
    {
     "expr": "nomad_client_allocations_running{cluster=\"$cluster\"}",
     "legendFormat": "allocations running"
    },
    {
     "expr": "100 -\nnomad_client_unallocated_cpu{role=\"nomad-client\"}\n/\n(nomad_client_allocated_cpu{role=\"nomad-client\"}\n+ nomad_client_unallocated_cpu{role=\"nomad-client\"}) * 100",
     "legendFormat": "cpu utilization"
    },
    {
     "expr": "100 -\nnomad_client_unallocated_memory{role=\"nomad-client\"}\n/\n(nomad_client_allocated_memory{role=\"nomad-client\"}\n+ nomad_client_unallocated_memory{role=\"nomad-client\"}) * 100",
     "legendFormat": "memory utilization"
    },
    {
     "expr": "100 -\nnomad_client_unallocated_disk{role=\"nomad-client\"}\n/\n(nomad_client_allocated_disk{role=\"nomad-client\"}\n+ nomad_client_unallocated_disk{role=\"nomad-client\"}) * 100",
     "legendFormat": "disk utilization"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace)(nomad_client_allocs_cpu_total_ticks{cluster=\"$cluster\"}) / sum by (namespace)(nomad_client_allocs_cpu_allocated{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace)(nomad_client_allocs_memory_usage{cluster=\"$cluster\"}) / sum by (namespace)(nomad_client_allocs_memory_allocated{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}