from enum import Enum


class LogCode(str, Enum):
    # System Events (SYSTEM*)
    SYSTEM = "SYSTEM"

    # Data Operations (DATA*)
    FILE_VALIDATION = "FILE_VALIDATION"
    DATA_STORAGE = "DATA_STORAGE"

    # Model Operations (MODEL*)
    MODEL_INFO = "MODEL_INFO"
    MODEL_SAVE = "MODEL_SAVE"
    MODEL_LOAD = "MODEL_LOAD"
    MODEL_INIT = "MODEL_INIT"
    MODEL_PREDICT = "MODEL_PREDICT"
    MODEL_TRAIN = "MODEL_TRAIN"
    MODEL_EVAL = "MODEL_EVAL"

    # NLP Token Operations (NLP_TOKEN_*)
    NLP_TOKEN_ADD_TAG = "NLP_TOKEN_ADD_TAG"
    NLP_TOKEN_BALANCING_SAMPLES = "NLP_TOKEN_BALANCING_SAMPLES"

    # Guardrails (GUARDRAILS*)
    GUARDRAILS = "GUARDRAILS"

    # Chat (CHAT*)
    CHAT = "CHAT"

    # NDB Specific Operations
    MODEL_INSERT = "MODEL_INSERT"
    MODEL_DELETE = "MODEL_DELETE"
    MODEL_RLHF = "MODEL_RLHF"

    LLM_CACHE = "LLM_CACHE"
