from enum import Enum


class LogCode(str, Enum):
    # Model Initialization (INIT_*)
    INIT_MODEL_START = "INIT_MODEL_START"
    INIT_MODEL_SUCCESS = "INIT_MODEL_SUCCESS"
    INIT_MODEL_FAILED = "INIT_MODEL_FAILED"
    INIT_BASE_MODEL_LOAD = "INIT_BASE_MODEL_LOAD"
    INIT_STORAGE_LOAD = "INIT_STORAGE_LOAD"

    # Data Operations (DATA_*)
    DATA_FILE_LOAD_START = "DATA_FILE_LOAD_START"
    DATA_FILE_LOAD_SUCCESS = "DATA_FILE_LOAD_SUCCESS"
    DATA_FILE_LOAD_FAILED = "DATA_FILE_LOAD_FAILED"
    DATA_FILE_INVALID = "DATA_FILE_INVALID"
    DATA_PARSE_ERROR = "DATA_PARSE_ERROR"
    DATA_STORAGE_INSERT = "DATA_STORAGE_INSERT"
    DATA_STORAGE_UPDATE = "DATA_STORAGE_UPDATE"
    DATA_CLEANUP_START = "DATA_CLEANUP_START"
    DATA_CLEANUP_COMPLETE = "DATA_CLEANUP_COMPLETE"

    # Model Training Operations (TRAIN_*)
    TRAIN_START = "TRAIN_START"
    TRAIN_COMPLETE = "TRAIN_COMPLETE"
    TRAIN_FAILED = "TRAIN_FAILED"
    TRAIN_PROGRESS = "TRAIN_PROGRESS"
    TRAIN_EPOCH_COMPLETE = "TRAIN_EPOCH_COMPLETE"
    TRAIN_METRICS_UPDATE = "TRAIN_METRICS_UPDATE"

    # Model Evaluation (EVAL_*)
    EVAL_START = "EVAL_START"
    EVAL_COMPLETE = "EVAL_COMPLETE"
    EVAL_FAILED = "EVAL_FAILED"
    EVAL_METRICS_UPDATE = "EVAL_METRICS_UPDATE"

    # Model Save/Load Operations (MODEL_*)
    MODEL_SAVE_START = "MODEL_SAVE_START"
    MODEL_SAVE_SUCCESS = "MODEL_SAVE_SUCCESS"
    MODEL_SAVE_FAILED = "MODEL_SAVE_FAILED"
    MODEL_LOAD_START = "MODEL_LOAD_START"
    MODEL_LOAD_SUCCESS = "MODEL_LOAD_SUCCESS"
    MODEL_LOAD_FAILED = "MODEL_LOAD_FAILED"

    # Guardrails Specific (GUARDRAILS_*)
    GUARDRAILS_TAG_ADD = "GUARDRAILS_TAG_ADD"
    GUARDRAILS_RULE_ADD = "GUARDRAILS_RULE_ADD"
    GUARDRAILS_RULE_FAILED = "GUARDRAILS_RULE_FAILED"
    GUARDRAILS_BALANCING_START = "GUARDRAILS_BALANCING_START"
    GUARDRAILS_BALANCING_COMPLETE = "GUARDRAILS_BALANCING_COMPLETE"

    # NDB Specific Operations (NDB_*)
    NDB_INSERT_START = "NDB_INSERT_START"
    NDB_INSERT_COMPLETE = "NDB_INSERT_COMPLETE"
    NDB_INSERT_FAILED = "NDB_INSERT_FAILED"
    NDB_DELETE_DOC = "NDB_DELETE_DOC"
    NDB_SUPERVISED_START = "NDB_SUPERVISED_START"
    NDB_SUPERVISED_COMPLETE = "NDB_SUPERVISED_COMPLETE"
    NDB_PARSE_START = "NDB_PARSE_START"
    NDB_PARSE_FAILED = "NDB_PARSE_FAILED"
    NDB_RLHF_START = "NDB_RLHF_START"
    NDB_RLHF_COMPLETE = "NDB_RLHF_COMPLETE"

    # Resource Management (RESOURCE_*)
    RESOURCE_DISK_CHECK = "RESOURCE_DISK_CHECK"
    RESOURCE_DISK_LOW = "RESOURCE_DISK_LOW"
    RESOURCE_MEMORY_CHECK = "RESOURCE_MEMORY_CHECK"
    RESOURCE_MEMORY_LOW = "RESOURCE_MEMORY_LOW"

    # Performance Monitoring (PERF_*)
    PERF_LATENCY_CHECK = "PERF_LATENCY_CHECK"
    PERF_SIZE_CHECK = "PERF_SIZE_CHECK"
    PERF_METRIC_UPDATE = "PERF_METRIC_UPDATE"

    # Report Generation (REPORT_*)
    REPORT_GENERATION_START = "REPORT_GENERATION_START"
    REPORT_GENERATION_COMPLETE = "REPORT_GENERATION_COMPLETE"
    REPORT_SAVE_SUCCESS = "REPORT_SAVE_SUCCESS"
    REPORT_SAVE_FAILED = "REPORT_SAVE_FAILED"

    # System Events (SYS_*)
    SYS_CONFIG_LOAD = "SYS_CONFIG_LOAD"
    SYS_CONFIG_ERROR = "SYS_CONFIG_ERROR"
    SYS_CLEANUP_START = "SYS_CLEANUP_START"
    SYS_CLEANUP_COMPLETE = "SYS_CLEANUP_COMPLETE"
