from enum import Enum


class LogCode(str, Enum):
    # Pydantic Validation Errors (PYDANTIC_*)
    PYDANTIC_VALIDATION = "PYDANTIC_VALIDATION"

    # Data Operations (DATA_*)
    DATA_FOLDER_CREATE = "DATA_FOLDER_CREATE"
    DATA_FILE_LOAD = "DATA_FILE_LOAD"
    DATA_FILE_INVALID = "DATA_FILE_INVALID"
    DATA_FILE_PARSE = "DATA_FILE_PARSE"

    DATA_STORAGE_CREATE = "DATA_STORAGE_CREATE"
    DATA_STORAGE_INSERT = "DATA_STORAGE_INSERT"
    DATA_STORAGE_UPDATE = "DATA_STORAGE_UPDATE"
    DATA_STORAGE_RETRIEVE = "DATA_STORAGE_RETRIEVE"

    DATA_CLEANUP = "DATA_CLEANUP"

    # Model Training Operations (TRAIN_*)
    MODEL_TRAIN = "MODEL_TRAIN"
    MODEL_TRAIN_EPOCH = "MODEL_TRAIN_EPOCH"
    MODEL_TRAIN_METRICS = "MODEL_TRAIN_METRICS"

    # Model Evaluation (EVAL_*)
    MODEL_EVAL = "MODEL_EVAL"
    MODEL_EVAL_METRICS = "MODEL_EVAL_METRICS"

    # Model Operations (MODEL_*)
    MODEL_INFO = "MODEL_INFO"
    MODEL_DEBUG = "MODEL_DEBUG"
    MODEL_SAVE = "MODEL_SAVE"
    MODEL_LOAD = "MODEL_LOAD"
    MODEL_INIT = "MODEL_INIT"
    MODEL_PREDICT = "MODEL_PREDICT"

    # NLP MODEL OPERATIONS (NLP_*)
    NLP_MODEL_LOAD = "NLP_MODEL_LOAD"
    NLP_MODEL_SAVE = "NLP_MODEL_SAVE"
    NLP_MODEL_INIT = "NLP_MODEL_INIT"
    NLP_MODEL_PREDICT = "NLP_MODEL_PREDICT"

    # NLP_TOKEN (NLP_TOKEN_*)
    NLP_TOKEN_ADD_TAG = "NLP_TOKEN_ADD_TAG"
    NLP_TOKEN_ADD_RULE = "NLP_TOKEN_ADD_RULE"
    NLP_TOKEN_GET_BALANCING_SAMPLES = "NLP_TOKEN_GET_BALANCING_SAMPLES"

    # GUARDRAILS (GUARDRAILS_*)
    GUARDRAILS_INFO = "GUARDRAILS_INFO"
    GUARDRAILS_INIT = "GUARDRAILS_INIT"

    # CHAT OPERATIONS (CHAT_*)
    CHAT_INIT = "CHAT_INIT"

    # NDB Specific Operations (NDB_*)
    NDB_LOAD = "NDB_LOAD"
    NDB_SAVE = "NDB_SAVE"
    NDB_INSERT = "NDB_INSERT"
    NDB_DELETE = "NDB_DELETE"
    NDB_SUPERVISED = "NDB_SUPERVISED"
    NDB_UPVOTE = "NDB_UPVOTE"
    NDB_ASSOCIATE = "NDB_ASSOCIATE"

    # Resource Management (RESOURCE_*)
    RESOURCE_DISK_CHECK = "RESOURCE_DISK_CHECK"
    RESOURCE_DISK_LOW = "RESOURCE_DISK_LOW"
    RESOURCE_MEMORY_CHECK = "RESOURCE_MEMORY_CHECK"
    RESOURCE_MEMORY_LOW = "RESOURCE_MEMORY_LOW"

    # Performance Monitoring (PERF_*)
    PERF_LATENCY_CHECK = "PERF_LATENCY_CHECK"
    PERF_SIZE_CHECK = "PERF_SIZE_CHECK"
    PERF_METRIC_UPDATE = "PERF_METRIC_UPDATE"

    # HTTP_REQUESTS EVENTS (HTTP_REQUEST_*)
    HTTP_REQUEST = "HTTP_REQUEST"

    # DEPLOYMENT EVENTS (DEPLOYMENT_*)
    DEPLOYMENT_INFO = "DEPLOYMENT_INFO"
    DEPLOYMENT_BAD_REQUEST = "DEPLOYMENT_BAD_REQUEST"
    DEPLOYMENT_INIT = "DEPLOYMENT_INIT"
