apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-cache
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .IngressHostname }}
      http:
        paths:
          - path: /cache/
            pathType: Prefix
            backend:
              service:
                name: llm-cache
                port:
                  number: 80
