apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-cache
spec:
  rules:
    - http:
        paths:
          - path: /cache/
            pathType: Prefix
            backend:
              service:
                name: llm-cache
                port:
                  number: 80
