apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .JobName }}"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        job-name: "{{ .JobName }}"
    spec:
      restartPolicy: Never
      containers:
      - name: backend
        image: "{{ .Driver.Registry }}/{{ .Driver.ImageName }}:{{ .Driver.Tag }}"
        imagePullPolicy: Always
        command: ["python3"]
        args: ["-m", "train_job.run", "--config", "{{ .ConfigPath }}"]
        env:
          {{- with .CloudCredentials }}
          - name: AWS_ACCESS_KEY
            value: "{{ .AwsAccessKey }}"
          - name: AWS_ACCESS_SECRET
            value: "{{ .AwsAccessSecret }}"
          - name: AWS_REGION_NAME
            value: "{{ .AwsRegionName }}"
          - name: AZURE_ACCOUNT_NAME
            value: "{{ .AzureAccountName }}"
          - name: AZURE_ACCOUNT_KEY
            value: "{{ .AzureAccountKey }}"
          - name: GCP_CREDENTIALS_FILE
            value: "{{ .GcpCredentialsFile }}"
          {{- end }}
          - name: HF_HOME
            value: "/model_bazaar/pretrained-models"
        resources:
          requests:
            cpu: "1"
            memory: "500Mi"
          limits:
            memory: "500Mi"
        volumeMounts:
          - name: shared-modelbazaar
            mountPath: "/model_bazaar"
      imagePullSecrets:
        - name: docker-credentials-secret
      volumes:
        - name: shared-modelbazaar
          {{- if eq .Platform "local" }}
          PersistentVolumeClaim:
            claimName: modelbazaar-local-pvc
          {{- else }}
          persistentVolumeClaim:
            claimName: modelbazaar-efs-pvc
          {{- end }}
