apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-dispatch
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  tls:
    - hosts:
        - {{ .IngressHostname }}
      secretName: thirdai-platform-tls
  rules:
    - host: {{ .IngressHostname }}
      http:
        paths:
          - path: /llm-dispatch/
            pathType: Prefix
            backend:
              service:
                name: llm-dispatch
                port:
                  number: 80
