apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-dispatch
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .IngressHostname }}
      http:
        paths:
          - path: /llm-dispatch/
            pathType: Prefix
            backend:
              service:
                name: llm-dispatch
                port:
                  number: 80
    {{- if eq .Platform "local" }}
    - host: host.minikube.internal
      http:
      paths:
        - path: /llm-dispatch/
        pathType: Prefix
        backend:
          service:
          name: llm-dispatch
          port:
            number: 80
    {{- end }}



{{- if ne .Platform "local" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-dispatch-internal
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx-internal
  rules:
    - host: thirdai-internal-ingress-nginx-controller.{{ namespace }}.svc.cluster.local
      http:
        paths:
          - path: /llm-dispatch/
            pathType: Prefix
            backend:
              service:
                name: llm-dispatch
                port:
                  number: 80
{{- end }}