apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thirdai-platform-frontend
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .IngressHostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thirdai-platform-frontend
                port:
                  number: 3000
