apiVersion: v1
kind: Service
metadata:
  name: thirdai-platform-frontend
  labels:
    app: thirdai-platform-frontend
spec:
  selector:
    app: thirdai-platform-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
