{
 "title": "Natural text model",
 "description": "Tracks the performance, trends and usage of a NLP model",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated,exported_job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queries Processed",
   "type": "timeseries",
   "description": "Number of queries processed",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (udt_predict_count{job=\"deployment-jobs\",workload=\"$workload\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Average inference time (in sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum (udt_predict_sum{job=\"deployment-jobs\",workload=\"$workload\"}) / sum (udt_predict_count{job=\"deployment-jobs\",workload=\"$workload\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "description": "Rate at which query is being fired",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(sum (udt_predict_count{job=\"deployment-jobs\",workload=\"$workload\"}))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Average Query Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum (udt_query_length_sum{job=\"deployment-jobs\",workload=\"$workload\"}) / sum (udt_query_length_count{job=\"deployment-jobs\",workload=\"$workload\"})",
     "legendFormat": "value"
    }
   ]
  }
 ]
}