{
 "title": "Allocations",
 "tags": [
  "nomad",
  "nomad-allocs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(nomad_client_uptime, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated{cluster=\"$cluster\",namespace=\"$namespace\"}, exported_job)"
    }
   },
   {
    "name": "group",
    "label": "Task Group",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated{cluster=\"$cluster\",namespace=\"$namespace\",exported_job=\"$workload\"}, task_group)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization %",
   "type": "timeseries",
   "description": "Total CPU resources consumed out of allocated",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (task) (nomad_client_allocs_cpu_total_ticks{exported_job=\"$workload\",task_group=\"$group\"}) / sum by (task) (nomad_client_allocs_cpu_allocated{exported_job=\"$workload\",task_group=\"$group\"})",
     "legendFormat": "{{task}} - {{alloc_id}}"
    }
   ]
  },
  {
   "title": "CPU Allocated",
   "type": "timeseries",
   "description": "Total CPU resources allocated across all cores",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "sum by (task)(nomad_client_allocs_cpu_allocated\t{exported_job=\"$workload\",task_group=\"$group\"})",
     "legendFormat": "{{task}} - {{alloc_id}}"
    }
   ]
  },
  {
   "title": "CPU Throttled Time ",
   "type": "timeseries",
   "description": "Total time that the task was throttled",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (task)(nomad_client_allocs_cpu_throttled_time{exported_job=\"$workload\",task_group=\"$group\"})",
     "legendFormat": "{{task}} - {{alloc_id}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Memory utilization %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (task)(nomad_client_allocs_memory_usage{exported_job=\"$workload\",task_group=\"$group\"}) / sum by (task)(nomad_client_allocs_memory_allocated{exported_job=\"$workload\",task_group=\"$group\"})",
     "legendFormat": "{{task}} - {{alloc_id}}"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "timeseries",
   "description": "Amount of memory allocated",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (task)(nomad_client_allocs_memory_allocated{exported_job=\"$workload\",task_group=\"$group\"}) / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Amount of memory consumed by the task",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (task)(nomad_client_allocs_memory_usage{exported_job=\"$workload\",task_group=\"$group\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}