{
 "title": "Clients",
 "tags": [
  "nomad",
  "nomad-clients"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(nomad_client_uptime, cluster)"
    }
   },
   { "name": "client_id", "label": "Client ID", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current cpu utilization",
   "type": "stat",
   "description": "% CPU utilization of the node",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster,instance) (nomad_client_host_cpu_total{cluster=\"$cluster\",instance=\"$client_id\"}) / (sum by (cluster, instance) (nomad_client_host_cpu_total{cluster=\"$cluster\",instance=\"$client_id\"}) + sum by (cluster, instance) (nomad_client_host_cpu_idle{cluster=\"$cluster\",instance=\"$client_id\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current memory utilisation",
   "type": "stat",
   "description": "% Memory utilization of the node",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster, instance) (nomad_client_host_memory_used{cluster=\"$cluster\", instance=\"$client_id\"}) / (sum by (cluster, instance) (nomad_client_host_memory_total{cluster=\"$cluster\", instance=\"$client_id\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilisation",
   "type": "stat",
   "description": "% Disk space being used",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster, instance) (nomad_client_host_disk_used{cluster=\"$cluster\", instance=\"$client_id\"}) / (sum by (cluster, instance) (nomad_client_host_disk_size{cluster=\"$cluster\", instance=\"$client_id\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clients",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "nomad_client_uptime{cluster=\"$cluster\"}",
       "legendFormat": "uptime"
      },
      {
       "expr": "nomad_client_allocations_running{cluster=\"$cluster\"}",
       "legendFormat": "allocations running"
      },
      {
       "expr": "100 -\nnomad_client_unallocated_cpu{role=\"nomad-client\"}\n/\n(nomad_client_allocated_cpu{role=\"nomad-client\"}\n+ nomad_client_unallocated_cpu{role=\"nomad-client\"}) * 100",
       "legendFormat": "cpu utilization"
      },
      {
       "expr": "100 -\nnomad_client_unallocated_memory{role=\"nomad-client\"}\n/\n(nomad_client_allocated_memory{role=\"nomad-client\"}\n+ nomad_client_unallocated_memory{role=\"nomad-client\"}) * 100",
       "legendFormat": "memory utilization"
      },
      {
       "expr": "100 -\nnomad_client_unallocated_disk{role=\"nomad-client\"}\n/\n(nomad_client_allocated_disk{role=\"nomad-client\"}\n+ nomad_client_unallocated_disk{role=\"nomad-client\"}) * 100",
       "legendFormat": "disk utilization"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Allocation",
   "type": "timeseries",
   "description": "% CPU shares allocated",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (cluster, instance) (nomad_client_allocated_cpu{cluster=\"$cluster\", instance=\"$client_id\"}) / (sum by (cluster, instance) (nomad_client_allocated_cpu{cluster=\"$cluster\", instance=\"$client_id\"}) + sum by (cluster, instance) (nomad_client_unallocated_cpu{cluster=\"$cluster\", instance=\"$client_id\"}))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "% CPU utilization out of allocated",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# https://discuss.hashicorp.com/t/clarification-on-the-nomad-client-allocs-cpu-total-percent-metric-for-docker-driver/17129/2\n# https://discuss.hashicorp.com/t/clarifications-on-nomad-metrics-values/64940/4\nsum by (cluster,instance) (nomad_client_allocs_cpu_total_ticks{cluster=\"$cluster\",instance=\"$client_id\"}) / sum by (cluster, instance) (nomad_client_allocs_cpu_allocated{cluster=\"$cluster\",instance=\"$client_id\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "# https://discuss.hashicorp.com/t/clarification-on-the-nomad-client-allocs-cpu-total-percent-metric-for-docker-driver/17129/2\n# https://discuss.hashicorp.com/t/clarifications-on-nomad-metrics-values/64940/4\nsum by (cluster,instance) (nomad_client_allocs_cpu_total_ticks{cluster=\"$cluster\",instance=\"$client_id\"})",
     "legendFormat": "CPU utilization"
    },
    {
     "expr": "sum by (cluster, instance) (nomad_client_allocated_cpu{cluster=\"$cluster\", instance=\"$client_id\"})",
     "legendFormat": "CPU allocated"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Memory Allocations",
   "type": "timeseries",
   "description": "% Memory allocated.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (cluster, instance) (nomad_client_allocated_memory{cluster=\"$cluster\", instance=\"$client_id\"}) / (sum by (cluster, instance) (nomad_client_allocated_memory{cluster=\"$cluster\", instance=\"$client_id\"}) + sum by (cluster, instance) (nomad_client_unallocated_memory{cluster=\"$cluster\", instance=\"$client_id\"}))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "description": "% Memory utilization out of allocated",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (cluster, instance)(nomad_client_allocs_memory_usage\t{cluster=\"$cluster\", instance=\"$client_id\"}) / sum by (cluster, instance)(nomad_client_allocs_memory_allocated {cluster=\"$cluster\", instance=\"$client_id\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster,instance) (nomad_client_allocs_memory_usage\t{cluster=\"$cluster\",instance=\"$client_id\"})",
     "legendFormat": "Memory utilization"
    },
    {
     "expr": "sum by (cluster, instance) (nomad_client_allocs_memory_allocated{cluster=\"$cluster\", instance=\"$client_id\"})",
     "legendFormat": "Memory allocated"
    }
   ]
  }
 ]
}