"""add hidden field for models

Revision ID: 0cf6d2c3b648
Revises: 3718790136f0
Create Date: 2024-11-01 11:13:21.403450

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cf6d2c3b648"
down_revision: Union[str, None] = "3718790136f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "models", sa.Column("hidden", sa.Boolean(), nullable=False, default=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("models", "hidden")
    # ### end Alembic commands ###
