"""add job warnings

Revision ID: 1d6f40f1cadc
Revises: 3718790136f0
Create Date: 2024-11-08 20:04:47.910157

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1d6f40f1cadc"
down_revision: Union[str, None] = "3718790136f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_messages",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("model_id", sa.UUID(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column(
            "level", postgresql.ENUM("warning", "error", name="level"), nullable=False
        ),
        sa.Column("message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_messages_model_id"), "job_messages", ["model_id"], unique=False
    )
    op.drop_index("ix_job_errors_model_id", table_name="job_errors")
    op.drop_table("job_errors")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_errors",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("model_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "job_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "not_started",
                "starting",
                "in_progress",
                "stopped",
                "complete",
                "failed",
                name="status",
                create_type=False,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("message", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name="job_errors_model_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="job_errors_pkey"),
    )
    op.create_index("ix_job_errors_model_id", "job_errors", ["model_id"], unique=False)
    op.drop_index(op.f("ix_job_messages_model_id"), table_name="job_messages")
    op.drop_table("job_messages")
    # ### end Alembic commands ###
