"""Separate reset password

Revision ID: 263fef17a7b6
Revises: 28ab48540cd7
Create Date: 2024-10-07 17:12:43.884837

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "263fef17a7b6"
down_revision: Union[str, None] = "28ab48540cd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_resets",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("reset_code_hash", sa.String(), nullable=False),
        sa.Column("expiration_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.drop_column("users", "reset_password_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "reset_password_code", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_table("password_resets")
    # ### end Alembic commands ###
