"""deactivated_user

Revision ID: 27ca58c99d31
Revises: 1d6f40f1cadc
Create Date: 2024-12-23 17:44:43.252424

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27ca58c99d31"
down_revision: Union[str, None] = "1d6f40f1cadc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_deactivated", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_deactivated")
    # ### end Alembic commands ###
