"""Remove Log Table

Revision ID: 28ab48540cd7
Revises: f2b04f674b1e
Create Date: 2024-09-16 10:51:03.110890

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "28ab48540cd7"
down_revision: Union[str, None] = "f2b04f674b1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("log_model_index", table_name="logs")
    op.drop_index("log_user_index", table_name="logs")
    op.drop_table("logs")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_workflow_model_component", "workflow_models", type_="unique"
    )
    op.create_table(
        "logs",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("model_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("action", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"], ["models.id"], name="logs_model_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="logs_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="logs_pkey"),
    )
    op.create_index("log_user_index", "logs", ["user_id"], unique=False)
    op.create_index("log_model_index", "logs", ["model_id"], unique=False)
    # ### end Alembic commands ###
