"""add job error storage

Revision ID: 3718790136f0
Revises: 7750a526cecc
Create Date: 2024-10-28 11:48:09.908530

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3718790136f0"
down_revision: Union[str, None] = "7750a526cecc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_errors",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("model_id", sa.UUID(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "not_started",
                "starting",
                "in_progress",
                "stopped",
                "complete",
                "failed",
                name="status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_errors_model_id"), "job_errors", ["model_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_errors_model_id"), table_name="job_errors")
    op.drop_table("job_errors")
    # ### end Alembic commands ###
