{
 "title": "Nodes",
 "description": "Panels for the node metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods",
   "type": "table",
   "description": "Information about the pods on the node",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"thirdai-platform\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(node_cpu_seconds_total{mode!=\"idle\",node=\"$node\"}[5m])) / count by (node) (node_cpu_seconds_total{mode=\"idle\",node=\"$node\"})* 100",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "description": "CPU usage of node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(node_cpu_seconds_total{mode!=\"idle\",node=\"$node\"}[5m]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory utilization",
     "type": "timeseries",
     "description": "Memory utilization of the node",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{node=\"$node\"} * 100) / node_memory_MemTotal_bytes{node=\"$node\"})",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Memory being used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{node=\"$node\"} - node_memory_MemAvailable_bytes{node=\"$node\"}",
       "legendFormat": "value"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  }
 ]
}