{
 "title": "Pods",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_status_phase{namespace=\"thirdai-platform\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "table",
   "description": "Information about the pod",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(kube_pod_status_phase{namespace=\"thirdai-platform\", pod=\"$pod\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\", namespace=\"thirdai-platform\", container!=\"\"}[5m])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CPU utilization",
     "type": "timeseries",
     "description": "CPU utilization out of allocated",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\", namespace=\"thirdai-platform\", container!=\"\"}[5m])) by (container)\n/\nsum(kube_pod_container_resource_limits{pod=\"$pod\", namespace=\"thirdai-platform\", resource=\"cpu\", container!=\"\"}) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory utilization",
     "type": "timeseries",
     "description": "Memory actively in use.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"\",pod=\"$pod\", namespace=\"thirdai-platform\"}) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Memory utilization",
     "type": "timeseries",
     "description": "Memory utilization out of allocated",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{pod=\"$pod\", namespace=\"thirdai-platform\", container!=\"\"}) by (container)\n/\nsum(kube_pod_container_resource_limits{pod=\"$pod\", namespace=\"thirdai-platform\", resource=\"memory\", container!=\"\"}) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  }
 ]
}