apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telemetry
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .IngressHostname }}
      http:
        paths:
          - path: /grafana/
            pathType: Prefix
            backend:
              service:
                name: telemetry-service
                port:
                  number: 3000
          - path: /victorialogs/
            pathType: Prefix
            backend:
              service:
                name: telemetry-service
                port:
                  number: 9428
                  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telemetry-internal
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx-internal
  rules:
    - host: thirdai-internal-ingress-nginx-controller.{{ namespace }}.svc.cluster.local
      http:
        paths:
          - path: /victoriametrics/
            pathType: Prefix
            backend:
              service:
                name: telemetry-service
                port:
                  number: 8428
          - path: /victorialogs/
            pathType: Prefix
            backend:
              service:
                name: telemetry-service
                port:
                  number: 9428