apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telemetry
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
specs:
  - host: {{ .IngressHostname }}
    http:
      paths:
        - path: /grafana/
          pathType: Prefix
          backend:
            service:
              name: grafana-service
              port:
                number: 3000
        - path: /victorialogs/
          pathType: Prefix
          backend:
            service:
              name: victorialogs-service
              port:
                number: 9428