apiVersion: v1
kind: ServiceAccount
metadata:
  name: victoriametrics-sa
  namespace: {{ namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: victoriametrics-k8s-discovery
rules:
  - apiGroups: 
      - ""
    resources:
      - services
      - nodes
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: victoriametrics-k8s-discovery
subjects:
  - kind: ServiceAccount
    name: victoriametrics-sa
    namespace: {{ namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: victoriametrics-k8s-discovery
  kind: ClusterRole