apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: victoriametrics-k8s-discovery
rules:
  - apiGroups: 
      - ""
    resources:
      - services
      - nodes
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch