docker_build(
  ref="thirdaiplatform.azurecr.io/thirdai_platform_jobs_local-dev",
  context="/Users/pratikqpranav/ThirdAI/Thirdai-Platform-v2/thirdai_platform_py",
  dockerfile="/Users/pratikqpranav/ThirdAI/Thirdai-Platform-v2/thirdai_platform_py/Dockerfile",
  extra_tag=["thirdaiplatform.azurecr.io/thirdai_platform_jobs_local-dev:latest"],     
)

docker_build(
  ref="thirdaiplatform.azurecr.io/thirdai_platform_local-dev",
  context="/Users/pratikqpranav/ThirdAI/Thirdai-Platform-v2/thirdai_platform",
  dockerfile="/Users/pratikqpranav/ThirdAI/Thirdai-Platform-v2/thirdai_platform/Dockerfile",
  extra_tag=["thirdaiplatform.azurecr.io/thirdai_platform_local-dev:latest"],     
)

docker_build(
  ref="thirdaiplatform.azurecr.io/frontend_local-dev",
  context="/Users/pratikqpranav/ThirdAI/Thirdai-Platform-v2/frontend",
  dockerfile="/Users/pratikqpranav/ThirdAI/Thirdai-Platform-v2/frontend/Dockerfile",
  extra_tag=["thirdaiplatform.azurecr.io/frontend_local-dev:latest"],     
)

k8s_yaml("deployment.yaml")
k8s_yaml("/opt/model_bazaar/jobs/thirdai-platform-frontend.yaml")

# jobYamlsOutput = str(local("find /opt/model_bazaar/jobs -maxdepth 1 -type f -name '*.yaml'", quiet=True))
# jobYamls = jobYamlsOutput.strip().split("\n")

# k8s_yaml(jobYamls)