apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .JobName }}"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: datagen
          image: "{{ .Registry }}/{{ .ImageName }}:{{ .Tag }}"
          command: ["python3"]
          args:
            - "-m"
            - "data_generation_job.run"
            - "--config"
            - "{{ .DatagenConfigPath }}"
          env:
            - name: GENAI_KEY
              value: "{{ .GenaiKey }}"
          resources:
            requests:
              cpu: "{{ .AllocationMhz }}"
              memory: "{{ .AllocationMemory }}"
            limits:
              memory: "{{ .AllocationMemoryMax }}"
          volumeMounts:
            - name: shared-modelbazaar
              mountPath: /model_bazaar

      containers:
        - name: backend
          image: "{{ .Registry }}/{{ .ImageName }}:{{ .Tag }}"
          command: ["python3"]
          args:
            - "-m"
            - "train_job.run"
            - "--config"
            - "{{ .ConfigPath }}"
          env:
            - name: AWS_ACCESS_KEY
              value: "{{ .AwsAccessKey }}"
            - name: AWS_ACCESS_SECRET
              value: "{{ .AwsAccessSecret }}"
            - name: AWS_REGION_NAME
              value: "{{ .AwsRegionName }}"
            - name: AZURE_ACCOUNT_NAME
              value: "{{ .AzureAccountName }}"
            - name: AZURE_ACCOUNT_KEY
              value: "{{ .AzureAccountKey }}"
            - name: GCP_CREDENTIALS_FILE
              value: "{{ .GcpCredentialsFile }}"
          resources:
            requests:
              cpu: "{{ .AllocationMhz }}"
              memory: "{{ .AllocationMemory }}"
            limits:
              memory: "{{ .AllocationMemoryMax }}"
          volumeMounts:
            - name: shared-modelbazaar
              mountPath: /model_bazaar

      volumes:
        - name: shared-modelbazaar
          persistentVolumeClaim:
            claimName: modelbazaar-efs-pvc
